name: Release
on:
  push:
    tags:
      - 'v*'
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.x

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --rm-dist # use .goreleaser.yml file in the root directory for configuration automatically
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # change Workflow permissions as Read and write permissions in Settings > Actions > General
